import "./globals.css";
import type { Metadata } from "next";
import Header from "@/components/layout/Header";
import { Chakra_Petch } from "next/font/google";
import Footer from "@/components/layout/Footer";
import ContactBtns from "@/components/layout/ContactBtns";

const chakra = Chakra_Petch({
  subsets: ["vietnamese"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={chakra.className}>
        <Header />
        {children}
        <Footer />
        <ContactBtns />
      </body>
    </html>
  );
}
